[package]
name = "ashuffle"
version = "0.0.0"
publish = false

[[bin]]
name = "ashuffle"

[dependencies]
libc = { git = "https://github.com/palfrey/libc.git", branch="strcase-various"}
easycurses = "0.12"

[build-dependencies]
cc = "1"